services:
  - type: web
    name: dash-onda-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python main.py"
    envVars:
      - key: PORT
        value: 4000
      - key: GOOGLE_SHEET_BAR_URL
        value: https://docs.google.com/spreadsheets/d/1C68_TiIwrYjuFszxdJmiIUwq7Kk42MIMv2-ysOSFpR4/export?format=csv&gid=0
      - key: GOOGLE_SHEET_VENDAS_URL
        value: https://docs.google.com/spreadsheets/d/1hHFo0sJnh4nAQbo0U2R1Kx95KTbyuImMu_C67YgELm0/export?format=csv&gid=0
      - key: GOOGLE_SHEET_URL
        value: https://docs.google.com/spreadsheets/d/1t1KVI9E6GanMnrNR55U0ssM46GBiWN_d5Ux9qVACDi8/export?format=csv
